version = 0.1
[default.deploy.parameters]
stack_name = "s3_presigned_url"
resolve_s3 = true
s3_prefix = "s3_presigned_url"
region = "ap-northeast-1"
profile = "localstack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
